### ISSUE TITLE
Missing file "inc\instarray.inc"; unable to compile and install package

### ISSUE THREAD

**Issue by CieloInvernale** [SAmeis/fpowm#1]
Lazarus seems unable to compile and install this package and ends compile task with a "panic" message.

Looks like there's a missing file in the package: "inc\instarray.inc".

Tested with Lazarus 1.6, FPC 3.0.0, Win 64 (Windows 10).

**Comment by SAmeis** [comment]
Hello @CieloInvernale,
thank you very much for your interest in this library.
I've updated the source code to be compilable on Windows; the file inc\instarray.inc doesn't matter at  all, but I had missed some other files and code changes.
